name: ðŸž Bug Report
description: Submit a bug report to help us improve, or to simply point out something that's broken.
title: '[Bug]: '
labels: ['bug']
assignees: ['davidjerleke']
body:
  - type: markdown
    attributes:
      value: |
        **Thanks :heart: for taking the time to fill out this bug report!**
        We kindly ask that you search to see if an issue [already exists](https://github.com/davidjerleke/embla-carousel/issues?q=is%3Aissue+sort%3Acreated-desc+) for your bug.
        If you're unsure if this is a bug or not, please create a [new discussion](https://github.com/davidjerleke/embla-carousel/discussions/new?category=help) instead!

        We are happy to accept contributions from our users. For more details see [here](https://github.com/davidjerleke/embla-carousel/blob/master/CONTRIBUTING.md#bug-reports).

  - type: checkboxes
    id: relations
    attributes:
      label: Which variants of Embla Carousel are you using?
      description: Check all that apply.
      options:
        - label: embla-carousel **(Core)**
        - label: embla-carousel-react
        - label: embla-carousel-vue
        - label: embla-carousel-svelte
        - label: embla-carousel-autoplay
        - label: embla-carousel-auto-scroll
        - label: embla-carousel-solid
        - label: embla-carousel-auto-height
        - label: embla-carousel-class-names
        - label: embla-carousel-fade
        - label: embla-carousel-docs **(Documentation)**
        - label: embla-carousel-docs **(Generator)**

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: A step-by-step description of how to reproduce the bug.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
      value: 'The bug occurs when I...'
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: What should have happened?
      placeholder: Tell us what you expected to happen!
      value: 'Fancy feature should have...'
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
      placeholder: ex. screenshots, stack traces, related issues, suggestions on how to fix, Stack Overflow links, forum links, etc.
      value: 'I have also tried...'
    validations:
      required: false

  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
        - All browsers

  - type: input
    id: version
    attributes:
      label: Version
      description: Which version of Embla Carousel are you using?
      placeholder: ex. v8.0.0
    validations:
      required: false

  - type: input
    id: codesandbox
    attributes:
      label: CodeSandbox
      description: |
        A link to a CodeSandbox that clearly reproduces the issue.

        > [!CAUTION]  
        > Skipping this or providing an invalid link may result in the issue being closed or even deleted without any warning.

      placeholder: ex. https://codesandbox.io/s/fancy-example-smu
    validations:
      required: false

  - type: checkboxes
    id: terms
    attributes:
      label: Before submitting
      description: By submitting this issue, you agree to follow our [Contributing Guidelines](https://github.com/davidjerleke/embla-carousel/blob/master/CONTRIBUTING.md).
      options:
        - label: I've made research efforts and searched the documentation
          required: true
        - label: I've searched for existing issues
          required: true
        - label: I agree to follow this project's Contributing Guidelines for bug reports
          required: true
