export { EmblaOptionsType } from './components/Options'
export { EmblaEventType } from './components/EventHandler'
export { EmblaPluginType } from './components/Plugins'
export { EmblaCarouselType } from './components/EmblaCarousel'
export { default } from './components/EmblaCarousel'
