name: Continuous Integration

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [24.x]

    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies 🔧
        run: yarn install --frozen-lockfile

      - name: Build 🏗️
        run: yarn build

      - name: Lint 🧐
        run: yarn lint

      - name: Test 🚨
        run: yarn test
